language:
  - cpp

compiler:
  - gcc

env:
  global:
    secure: PFqvUe6tt5WTCzOfq4/9F2Pt5Kvy2DYWSVQlkDP4THPEtGvtJCBHjE2jt3QuTGQrmWsARhOG8MZRY6i4i+zvEnPhZOM938ghAEV+d3REv4Up1Bj4lG2kIyjAQh2lZomecUaY0IBC+PfzhQOvmvNazNYKncEgziz0/QKXCrPkN/U=
# comment back in after  PR creation works
# before_install:
#   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#   - sudo apt-get update -qq
#   - sudo apt-get install libc6-dbg
#   - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
#   - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
#   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; alias g++="g++-4.8"; alias gcc="gcc-4.8"; fi
#   - wget https://s3.amazonaws.com/public-unit-test-resources/valgrind-3.10.1.tar.bz2 && tar xjvf valgrind-3.10.1.tar.bz2
#   - cd valgrind-3.10.1 && ./configure && make
#   - sudo make install
  
script:
  # comment back in after PR creation works
  # - cd $TRAVIS_BUILD_DIR/Plugins/FastScaling/NativeFastScaling
  # - rake test
  # - rake clean
  # - rake valgrind
  # - rake test_with_valgrind
  - cd ${TRAVIS_BUILD_DIR}/Tools/DocCollector
  # delete after PR creation works 
  - unset TRAVIS_PULL_REQUEST
  - ./doccollector.sh
